name: My Starter Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to promote to'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - test
        - production
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
          
  call-reusable-workflow:
    needs: build
    strategy:
      matrix:
        nodeversion: [14,16,18,20]
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: ${{ matrix.nodeversion }}
      environment: development
          
