name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string
      environment:
        required: true
        type: string
        
jobs: 

  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Output the input value
        run: |
         echo "The node version to use is: ${{ inputs.node }}"

      - name: Output the input value
        run: |
          echo "Code is deployed to: ${{ inputs.environment }} ${{secrets.description}}"

